### PR TITLE
pub ack response with pub ack object in definitions.json

### PR DESCRIPTION
**Pull request by scottf**

### CODE REVIEW

**Comment by ripienaar** [comment]
definitions.json is there for objects that are reused between multiple schemas, so when maintaining pub_ack_response I go to that file, and only the sections that is shared between schemas is not in the file.  In the case of these 2 the parts this PR moves into definitions.json is not reused, so why move them? Moving them seem to contribute to the already hard to maintain/navigate definitions.json without improving the DRYness of the files or readability/maintainability of them

**Comment by scottf** [comment]
I was trying to address missing uint64. It's seems better to have all object definitions in one place. I would argue that those 2 places that did not get updated to use `"$ref": "#/definitions/golang_uint64"` would not have been missed if the it were the case that the objects were in one place, making it easier, not harder to maintain.

**Comment by ripienaar** [comment]
I didnt update them by looking at the schemas, I updated them by looking at the go code - so missing them is unrelated to where they are in schemas.

The layout of these schemas are consistent, only reused items go into definitions.json, see other examples:

consumer_delete_response
consumer_getnext_request
consumer_leader_stepdown_response
consumer_names_response
meta_leader_stepdown_response
meta_server_remove_response

and many more, so I prefer to keep them in the files where they belong, keeping definitions.json only for definitions reused by multiple schemas.

**Comment by scottf** [comment]
replaced with https://github.com/nats-io/jsm.go/pull/305

**Pull request closed without merging**
