### PR TITLE
Add support FileStorage into KV

### PR DESCRIPTION
**Pull request by NikitaDef**

### CODE REVIEW

**Comment by NikitaDef** [comment]
@ripienaar what do you think about the MR?

**Comment by ripienaar** [comment]
File storage is the default, this PR changes the default to memory storage - a very dangerous default.

When would you make a memory storage based KV? I guess if all you want is to use it as a cache perhaps.  But if anything we'd flip this around so file is default and then have a opt-in for memory storage.

Apart from that, at least in theory, we want to be portable as possible so we can replace the backend, so memory storage mgiht simply not make sense since other KVs dont have that as a concept

**Comment by NikitaDef** [comment]
Sorry, I use old nats-server old libs and I see memory store.  I close the MR
at page http://localhost:8222/jsz?streams=true&config=true&consumers=true&config=true&accounts=true

**Comment by ripienaar** [comment]
Oh yes we changed the default on the server because memory as default was quite scary. 

Thank you glad that’s sorted!

**Pull request closed without merging**
